---
- name: Create fstat systemd tmpfile
  shell: systemd-tmpfiles --create /etc/tmpfiles.d/fstat.conf

- name: Reload systemd
  shell: systemctl daemon-reload

- name: Restart fstat backend
  service:
    name: fstat
    state: restarted
