---
- hosts: proxy
  roles:

  - role: swap_file
    size: 1G
    path: /var/swap

# commented until the issue with ethernet swapping is debugged
# might have been the eth01 interface that cause trouble
#  - role: network_conf_ifcfg
#    interface: eth1
#    ip: "{{ internal_ip }}/24"

  - role: httpd_proxy
    website_domain: build.proxy.gluster.org
    reverse_proxy: http://8.43.85.172/
    use_mod_sec: True
    mod_sec_detection_only: True

  - role: httpd_proxy
    website_domain: review.proxy.gluster.org
    reverse_proxy: http://gerrit.rht.gluster.org/
    use_mod_sec: True
    mod_sec_detection_only: True

  - role: httpd_proxy
    website_domain: softserve.gluster.org
    reverse_proxy: http://softserve.rht.gluster.org/

  - role: httpd_proxy
    website_domain: fstat.gluster.org
    reverse_proxy: http://fstat.rht.gluster.org/
    server_aliases:
    - failurestat.gluster.org

  - role: httpd_proxy
    website_domain: analysis.gluster.org
    reverse_proxy: http://analysis.rht.gluster.org/

